version: "3.7"

networks:
  internal: 
    external: false # Create the network if it doesn't exist
    name: tensorflow_network

volumes:
  tensorflow_data_volume:
      external: false # Create the volume if it doesn't exist
      name: tensorflow_data

services: 
  # # ---------------------------------
  # # Tensorflow platform
  # # ---------------------------------

  tensorflow-worker: 
    container_name: tensorflow-worker
    build: 
      context: ./tensorflow
      dockerfile: Dockerfile
    restart: on-failure
    volumes: 
      - tensorflow_data_volume:/share/tensorflow
    ports: 
      - 8888:8888
    networks: 
      - internal
  