version: "3.7"

networks:
  internal: 
    external: false # Create the network if it doesn't exist
    name: tensorflow_network

volumes:
  tensorflow_data_volume:
      external: false # Create the volume if it doesn't exist
      name: tensorflow_data

services: 
  # # ---------------------------------
  # # Tensorflow platform
  # # ---------------------------------

  tensorflow-models: 
    container_name: tensorflow-models
    build: 
      context: ./tensorflow-models
      dockerfile: Dockerfile.cpu
      args:
        - LOCAL_TENSORFLOW_VERSION=latest
    restart: on-failure
    volumes: 
      - tensorflow_data_volume:/share/tensorflow
    ports: 
      - 8888:8888
    privileged: true
    cap_add:
      - ALL
    networks: 
      - internal
  